---
name: github-triage
description: Triage GitHub issues through a label-based state machine. Use when user wants to create an issue, triage issues, review incoming bugs or feature requests, prepare issues for an AFK agent, or manage issue workflow.
---

```makefile
# Variables
REPO = $(git remote)
DISCLAIMER = > *This was generated by AI during triage.*

# ── Labels ──────────────────────────────────────────────
# State labels:    needs-triage | needs-info | ready-for-agent | ready-for-human | wontfix
# Category labels: bug | enhancement
# Rule: each issue must have exactly one state label and one category label.
# If conflicting state labels exist, flag the conflict and ask the maintainer
# which state is correct before doing anything else. Provide a recommendation.

# ── State Machine ───────────────────────────────────────
# unlabeled    → needs-triage    | Skill (on first look)
# unlabeled    → ready-for-agent | Maintainer (via skill)
# unlabeled    → ready-for-human | Maintainer (via skill)
# unlabeled    → wontfix         | Maintainer (via skill)
# needs-triage → needs-info      | Maintainer (via skill)
# needs-triage → ready-for-agent | Maintainer (via skill)
# needs-triage → ready-for-human | Maintainer (via skill)
# needs-triage → wontfix         | Maintainer (via skill)
# needs-info   → needs-triage    | Skill (detects reply)
#
# Issues may only move along these transitions.
# Maintainer may override any state directly (see quick-override).
# Flag if a transition is unusual.

# ── Reference docs ──────────────────────────────────────
# AGENT-BRIEF.md   — how to write durable agent briefs
# OUT-OF-SCOPE.md  — how the .out-of-scope/ knowledge base works

# ── Main entry ──────────────────────────────────────────
# The maintainer invokes /github-triage then describes what they want
# in natural language. Interpret the request and take the appropriate action.
# Examples:
#   "Show me anything that needs my attention"
#   "Let's look at #42"
#   "Move #42 to ready-for-agent"
#   "What's ready for agents to pick up?"
#   "Are there any unlabeled issues?"

triage: show-needs-attention triage-issue quick-override

# ── Show what needs attention ───────────────────────────
show-needs-attention:
	@ gh issue list --repo $(REPO) --json number,title,createdAt,labels,body --limit 100
	? Query GitHub and present a summary grouped into three buckets:
	? 1. Unlabeled issues — new, no labels at all. Never triaged.
	? 2. needs-triage issues — maintainer needs to evaluate or continue evaluating.
	? 3. needs-info issues with new activity — reporter has commented since the last triage notes comment. Check comment timestamps to determine this.
	? Display counts per group. Within each group show issues oldest first (longest-waiting first).
	? For each issue show: number, title, age, one-line summary of the issue body.
	? Let the maintainer pick which issue to dive into.

# ── Triage a specific issue ─────────────────────────────
triage-issue: gather-context present-recommendation apply-outcome

gather-context:
	@ gh issue view $(ISSUE) --repo $(REPO) --json body,comments,labels,author,createdAt
	? Read the full issue: body, all comments, all labels, who reported it, when.
	? If there are prior triage notes comments (from previous sessions), parse them to understand what has already been established.
	? Explore the codebase to build context — understand the domain, relevant interfaces, and existing behavior related to the issue.
	@ ls .out-of-scope/*.md 2>/dev/null || true
	? Read .out-of-scope/*.md files and check if this issue matches or is similar to a previously rejected concept.

present-recommendation:
	? Tell the maintainer:
	? — Category recommendation: bug or enhancement, with reasoning.
	? — State recommendation: where this issue should go, with reasoning.
	? — If it matches a prior out-of-scope rejection, surface that: "This is similar to .out-of-scope/concept-name.md — we rejected this before because X. Do you still feel the same way?"
	? — A brief summary of what you found in the codebase that's relevant.
	? Then wait for the maintainer's direction. They may agree and ask to apply labels, want to flesh it out, override with a different state, or want to discuss.

reproduce-bug:
	? Only for issues categorized as bugs. Attempt to reproduce before starting a domain-model session.
	? Read the reporter's reproduction steps if provided. Explore the codebase to understand relevant code paths.
	? Try to reproduce: run tests, execute commands, or trace the logic to confirm the reported behavior.
	? If reproduction succeeds: report what you found — specific behavior observed and where in the code it originates.
	? If reproduction fails: report that — bug may be environment-specific, already fixed, or report may be inaccurate.
	? If the report lacks enough detail to attempt reproduction: note that — strong signal the issue should move to needs-info.

domain-model-session:
	$ /domain-model
	? If the issue needs to be fleshed out before it's ready for an agent, interview the maintainer to build a complete specification using the domain-model skill.

apply-outcome:
	ifeq ($(STATE), ready-for-agent)
		? Post an agent brief comment per AGENT-BRIEF.md. Prepend the AI disclaimer: $(DISCLAIMER)
	endif
	ifeq ($(STATE), ready-for-human)
		? Post a comment summarizing the task, what was established during triage, and why it needs human implementation.
		? Use the same structure as an agent brief but note the reason it can't be delegated to an agent
		? (e.g. requires judgment calls, external system access, design decisions, or manual testing).
		? Prepend the AI disclaimer: $(DISCLAIMER)
	endif
	ifeq ($(STATE), needs-info)
		? Post triage notes with progress so far and questions for the reporter using the needs-info-output format.
	endif
	ifeq ($(STATE), wontfix-bug)
		? Post a polite comment explaining why, then close the issue. Prepend the AI disclaimer: $(DISCLAIMER)
	endif
	ifeq ($(STATE), wontfix-enhancement)
		? Write to .out-of-scope/ per OUT-OF-SCOPE.md, post a comment linking to it, then close the issue.
		? Prepend the AI disclaimer: $(DISCLAIMER)
	endif
	ifeq ($(STATE), needs-triage)
		@ gh issue edit $(ISSUE) --repo $(REPO) --add-label "needs-triage"
		? Optionally leave a comment if there's partial progress to capture.
	endif

# ── Quick state override ────────────────────────────────
quick-override:
	? When the maintainer explicitly says to move an issue to a specific state
	? (e.g. "move #42 to ready-for-agent"), trust their judgment and apply the label directly.
	? Show a confirmation of what you're about to do: which labels will be added/removed,
	? and whether you'll post a comment or close the issue. Skip the domain-model session entirely.
	ifeq ($(STATE), ready-for-agent)
		? Ask the maintainer if they want to write a brief agent brief comment or skip it.
	endif
	@ gh issue edit $(ISSUE) --repo $(REPO) --add-label $(STATE)

# ── Needs Info output format ────────────────────────────
needs-info-output:
	? Post a comment with the following structure. Prepend the AI disclaimer: $(DISCLAIMER)
	? ## Triage Notes
	?
	? **What we've established so far:**
	?
	? - point 1
	? - point 2
	?
	? **What we still need from you (@reporter):**
	?
	? - question 1
	? - question 2
	?
	? Include everything resolved during the domain-model session in "established so far" —
	? this work should not be lost. Questions must be specific and actionable, not vague.

# ── Resume previous session ─────────────────────────────
resume-session:
	@ gh issue view $(ISSUE) --repo $(REPO) --json comments,labels
	? Read all comments to find prior triage notes. Parse what was already established.
	? Check if the reporter has answered any outstanding questions.
	? Present the maintainer with an updated picture:
	? "Here's where we left off, and here's what the reporter has said since."
	? Continue the domain-model session from where it stopped — do not re-ask resolved questions.
```
